### ISSUE TITLE
Test latest code of 2sxc on this 

### ISSUE THREAD

**Issue by iJungleboy** [2sic/app-dev-testing-permissions-and-save#2]

**Comment by tvatavuk** [comment]
In **2. Public Form UI Test** we have tests:

2.4. a content-type which has anonyomus schema permissions, and anonymous create-draft only
  - an anonymous user should be able to create an item, but it should be draft right away
  - an anonymous user should not be able to edit it

![image](https://user-images.githubusercontent.com/2724850/45996082-251e3280-c09b-11e8-9fa6-a775e1d19bdf.png)


2.5. a content-type which has anonyomus schema permissions, and anonymous edit-draft only
  - an anonymous user should not be able to create anything
  - an anonymous user should be able to edit, but the result should be draft

![image](https://user-images.githubusercontent.com/2724850/45996096-30715e00-c09b-11e8-9a1a-4a1a2818fc40.png)


I get same result in both tests, and is not as expected:
  - an anonymous user should be able to create an item, but it should be draft right away
  - an anonymous user should be able to edit, but the result should be draft

**Comment by iJungleboy** [comment]
I don't understand. What is the result you get?

**Comment by tvatavuk** [comment]
2.4. a content-type which has anonyomus schema permissions, and anonymous create-draft only

[expected] - anonymous user can create item and it is draft right away
[not expected] - anonymous user can edit public item and update become draft

2.5. a content-type which has anonyomus schema permissions, and anonymous edit-draft only

[not expected] - anonymous user can create item and it is draft right away
[expected] - anonymous user can edit public item and update become draft

**Comment by iJungleboy** [comment]
So if I understand you correctly

1. In the first case, the problem is that edit was actually allowed
1. in both cases, the problem is that the draft didn't branch, but made the item itself a draft

is that correct

**Comment by tvatavuk** [comment]
In **3. Semi-Public forms** we get two unexpected results:

![image](https://user-images.githubusercontent.com/2724850/45998689-e5a81400-c0a3-11e8-99c8-8637f0867c82.png)


[expected] - an anonymous user is not able to edit
[expected] - an anonymous user is not able to create
[not expected] - a user in that group is able to create published item **but it is not able to create draft**
[not expected] - a user in that group is able to edit published item **but not able to edit draft**
[expected] - a user in that group is able to delete

**Comment by tvatavuk** [comment]
>     1. In the first case, the problem is that edit was actually allowed

Yes, the problem is that edit of published item is allowed for anonymous user (still it is good that save will not update published item, but it will create new draft version of item)

>     2. in both cases, the problem is that the draft didn't branch, but made the item itself a draft

No (at least I do not see or understand that)

I second test (2.5.) I think we can have a problem with definition of 2.5. test (or my implementation because of understanding it in incorrect way). 
In definition of test it is expected that **"an anonymous user should not be able to create anything"** but it is defined to provide permission "anonymous edit-draft only".

![image](https://user-images.githubusercontent.com/2724850/46000070-dd51d800-c0a7-11e8-8dc6-58e49a913efd.png)

... so anonymous user can create item and it is draft right away.

**Comment by tvatavuk** [comment]
Related to 3 comments before, all looks great with latest version of code.

**2. Public Form UI Test**

1) test 2.4. a content-type which has anonyomus schema permissions, and anonymous create-draft only
- all as expected

2) test 2.5. a content-type which has anonyomus schema permissions, and anonymous edit-draft only
- all as expected

**3. Semi-Public forms UI Tests**

3) draft works as expected

**Comment by iJungleboy** [comment]
awesome :)
